/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSqliteRouteImport } from './routes/s/sqlite'
import { Route as SPythonRouteImport } from './routes/s/python'
import { Route as SPostgresRouteImport } from './routes/s/postgres'
import { Route as SPhpRouteImport } from './routes/s/php'
import { Route as SHtmlRouteImport } from './routes/s/html'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSqliteRoute = SSqliteRouteImport.update({
  id: '/s/sqlite',
  path: '/s/sqlite',
  getParentRoute: () => rootRouteImport,
} as any)
const SPythonRoute = SPythonRouteImport.update({
  id: '/s/python',
  path: '/s/python',
  getParentRoute: () => rootRouteImport,
} as any)
const SPostgresRoute = SPostgresRouteImport.update({
  id: '/s/postgres',
  path: '/s/postgres',
  getParentRoute: () => rootRouteImport,
} as any)
const SPhpRoute = SPhpRouteImport.update({
  id: '/s/php',
  path: '/s/php',
  getParentRoute: () => rootRouteImport,
} as any)
const SHtmlRoute = SHtmlRouteImport.update({
  id: '/s/html',
  path: '/s/html',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/html': typeof SHtmlRoute
  '/s/php': typeof SPhpRoute
  '/s/postgres': typeof SPostgresRoute
  '/s/python': typeof SPythonRoute
  '/s/sqlite': typeof SSqliteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/html': typeof SHtmlRoute
  '/s/php': typeof SPhpRoute
  '/s/postgres': typeof SPostgresRoute
  '/s/python': typeof SPythonRoute
  '/s/sqlite': typeof SSqliteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/html': typeof SHtmlRoute
  '/s/php': typeof SPhpRoute
  '/s/postgres': typeof SPostgresRoute
  '/s/python': typeof SPythonRoute
  '/s/sqlite': typeof SSqliteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/s/html'
    | '/s/php'
    | '/s/postgres'
    | '/s/python'
    | '/s/sqlite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/html' | '/s/php' | '/s/postgres' | '/s/python' | '/s/sqlite'
  id:
    | '__root__'
    | '/'
    | '/s/html'
    | '/s/php'
    | '/s/postgres'
    | '/s/python'
    | '/s/sqlite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SHtmlRoute: typeof SHtmlRoute
  SPhpRoute: typeof SPhpRoute
  SPostgresRoute: typeof SPostgresRoute
  SPythonRoute: typeof SPythonRoute
  SSqliteRoute: typeof SSqliteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/sqlite': {
      id: '/s/sqlite'
      path: '/s/sqlite'
      fullPath: '/s/sqlite'
      preLoaderRoute: typeof SSqliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/python': {
      id: '/s/python'
      path: '/s/python'
      fullPath: '/s/python'
      preLoaderRoute: typeof SPythonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/postgres': {
      id: '/s/postgres'
      path: '/s/postgres'
      fullPath: '/s/postgres'
      preLoaderRoute: typeof SPostgresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/php': {
      id: '/s/php'
      path: '/s/php'
      fullPath: '/s/php'
      preLoaderRoute: typeof SPhpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/html': {
      id: '/s/html'
      path: '/s/html'
      fullPath: '/s/html'
      preLoaderRoute: typeof SHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SHtmlRoute: SHtmlRoute,
  SPhpRoute: SPhpRoute,
  SPostgresRoute: SPostgresRoute,
  SPythonRoute: SPythonRoute,
  SSqliteRoute: SSqliteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
