import "dotenv/config";
import fs from "fs";
import { hideBin } from "yargs/helpers";
import { openrouter } from "@openrouter/ai-sdk-provider";
import { generateText, Output } from "ai";
import { z } from "zod/v4";
import yargs from "yargs";
import path from "path";
import process from "process";
import ora from "ora";
import chalk from "chalk";

yargs(hideBin(process.argv))
  .command(
    "$0 <files...>",
    "review the documents",
    (yargs) => {
      return yargs.positional("files", {
        describe: "list of files to review",
        type: "string",
        array: true,
      });
    },
    async (argv) => {
      if (!argv.files) return;

      for (const file of argv.files) {
        const spinner = ora({
          text: `Reviewing ${file}`,
        }).start();
        const content = fs.readFileSync(file, "utf-8");

        const { output } = await generateText({
          model: openrouter("openai/gpt-oss-120b:nitro"),
          system: `
          Your job is to review the document, and, if you find anything that needs to be improved, make a review with the range of lines and the suggested change. If there is no need for changes, return an empty array.
          There is no need to return the reviews if there are no changes needed, an empty array is a valid response. 
          The guidelines for writing a good quality document are the following contained in this skill:
          ${fs.readFileSync(path.join(__dirname, "../../../.agents/skills/writer/SKILL.md"), "utf-8")}
          `,
          prompt: content,
          output: Output.object({
            schema: z.object({
              reviews: z
                .array(
                  z.object({
                    lines: z
                      .string()
                      .regex(/\d+(--\d+)?/, "line range must be in format X, X-Y or X-Y,X-Y,X-Y...")
                      .describe("range of lines, ex. 4, 4-5, 7"),
                    review: z.string().describe("review of the lines"),
                  }),
                )
                .describe("reviews of the document"),
            }),
          }),
        });

        if (output.reviews.length === 0) {
          spinner.succeed(`No reviews needed for ${file}`);
          continue;
        }

        spinner.succeed(`Reviews found for ${file}`);
        for (const review of output.reviews) {
          console.log("At line(s) " + chalk.cyan(review.lines) + ":", chalk.yellow(review.review));
        }

        if (!fs.existsSync("dist")) {
          fs.mkdirSync("dist");
        }

        fs.writeFileSync(
          `dist/review-${crypto.randomUUID()}.md`,
          `# Review for ${file}\nThe autogenerated review for ${file} is:\n\n${output.reviews.map((review) => `## Lines: ${review.lines}\n${review.review}`).join("\n")}`,
        );
      }
    },
  )
  .parse();
