/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqliteRouteImport } from './routes/sqlite'
import { Route as HtmlRouteImport } from './routes/html'
import { Route as IndexRouteImport } from './routes/index'

const SqliteRoute = SqliteRouteImport.update({
  id: '/sqlite',
  path: '/sqlite',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlRoute = HtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/html': typeof HtmlRoute
  '/sqlite': typeof SqliteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/html': typeof HtmlRoute
  '/sqlite': typeof SqliteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/html': typeof HtmlRoute
  '/sqlite': typeof SqliteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/html' | '/sqlite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/html' | '/sqlite'
  id: '__root__' | '/' | '/html' | '/sqlite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HtmlRoute: typeof HtmlRoute
  SqliteRoute: typeof SqliteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sqlite': {
      id: '/sqlite'
      path: '/sqlite'
      fullPath: '/sqlite'
      preLoaderRoute: typeof SqliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html': {
      id: '/html'
      path: '/html'
      fullPath: '/html'
      preLoaderRoute: typeof HtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HtmlRoute: HtmlRoute,
  SqliteRoute: SqliteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
